import { CPUDifficulty, DifficultyConfig } from '../types/puyo';

export const DIFFICULTY_CONFIGS: Record<CPUDifficulty, DifficultyConfig> = {
  easy: {
    id: 'easy',
    name: 'かんたん',
    label: 'Easy',
    avatar: '/src/assets/images/avatar_cpu_easy_1790914638595.jpg',
    characterName: 'スライミー',
    title: 'ぷよぷよ初心者見習い',
    description: 'ゆったり考えてゆっくり落とす初心者向けCPU。ぷよを繋げる練習にぴったりです！',
    thinkSpeedMs: 550,
    dropSpeedMs: 800,
    chainTarget: '1〜2連鎖',
    aggressiveness: 1,
  },
  normal: {
    id: 'normal',
    name: 'ふつう',
    label: 'Normal',
    avatar: '/src/assets/images/avatar_cpu_normal_1790914653395.jpg',
    characterName: 'アリス',
    title: '魔法学園の元気少女',
    description: '同じ色をまとめて2〜3連鎖を狙ってくる標準的な実力者。おじゃま相殺もしてきます。',
    thinkSpeedMs: 280,
    dropSpeedMs: 500,
    chainTarget: '2〜3連鎖',
    aggressiveness: 3,
  },
  hard: {
    id: 'hard',
    name: 'むずかしい',
    label: 'Hard',
    avatar: '/src/assets/images/avatar_cpu_hard_1790914768342.jpg',
    characterName: 'シェイド',
    title: '冥界の凄腕魔導士',
    description: '階段積みや挟み込みを駆使して4〜5連鎖を狙う上級CPU。大ダメージに即座にカウンター！',
    thinkSpeedMs: 140,
    dropSpeedMs: 320,
    chainTarget: '3〜5連鎖',
    aggressiveness: 5,
  },
  expert: {
    id: 'expert',
    name: 'げきむず',
    label: 'Expert',
    avatar: '/src/assets/images/avatar_cpu_void_1790915816536.jpg',
    characterName: '魔王ヴォイド',
    title: '暗黒連鎖の覇王',
    description: '超高速思考と容赦のない5〜7連鎖で圧倒してくる最凶ボス。自信のある猛者専用！',
    thinkSpeedMs: 50,
    dropSpeedMs: 180,
    chainTarget: '5〜7連鎖+',
    aggressiveness: 8,
  },
};
